### ISSUE TITLE
get_merra2_subset error

### ISSUE THREAD

**Issue by jchawarski** [olugovoy/merra2ools#3]
Hi there, I'm getting the following error when running the get_merra2_subset() function:
"Error in lubridate::ymd_h(to, tz = tmz) : object 'tmz' not found"

I've tried various timezones using the OlsenNames conventions and tried different date ranges but no luck.
#codeexample
CP <- as(extent(-140, -120, 65, 75), "SpatialPolygons")
locid_CB <- get_locid(CP, method="points") # needs to get from spatialpolygons dataframe
merra_CB <- get_merra2_subset(locid = locid_CB, 
                              from = "20180101 00", to = "20180630 00",
                              tz="UTC")

**Comment by olugovoy** [comment]
Hi, thanks for reporting the bug. A quick workaround would be to assign `tmz` before calling the `get_merra2_subset`: 
`library(sf)`
`CP <- as(raster::extent(-140, -120, 65, 75), "SpatialPolygons")`
`sp::proj4string(CP) <- sp::CRS("+proj=longlat +datum=WGS84")`
`locid_CB <- get_locid(CP, method="points")`
`tmz <- "UTC"` # this should pass the time-zone to the `get_merra2_subset` function
`merra_CB <- get_merra2_subset(locid = locid_CB, from = fDate(2018, 01, 01, 0), to = fDate(2018, 01, 01, 23))`
We will fix the bug shortly.

**Comment by jchawarski** [comment]
Thanks! That worked.
